-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS "DB_schema".users
(
    id bigint NOT NULL,
    name text NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS "DB_schema".tickets
(
    id bigint NOT NULL,
    title text NOT NULL,
    descrption text,
    owner bigint NOT NULL,
    addicted_to bigint DEFAULT 0,
    majority integer,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS "DB_schema".lists
(
    id bigint NOT NULL,
    title text,
    description text,
    owner bigint NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS "DB_schema".users_lists
(
    users_id bigint NOT NULL,
    lists_id bigint NOT NULL
);

CREATE TABLE IF NOT EXISTS "DB_schema".lists_tickets
(
    lists_id bigint NOT NULL,
    tickets_id bigint NOT NULL
);

CREATE TABLE IF NOT EXISTS "DB_schema".majority_levels
(
    id integer NOT NULL,
    title text NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS "DB_schema".users
    ADD FOREIGN KEY (id)
    REFERENCES "DB_schema".tickets (addicted_to) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS "DB_schema".users
    ADD FOREIGN KEY (id)
    REFERENCES "DB_schema".tickets (owner) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS "DB_schema".users
    ADD FOREIGN KEY (id)
    REFERENCES "DB_schema".lists (owner) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS "DB_schema".tickets
    ADD FOREIGN KEY (majority)
    REFERENCES "DB_schema".majority_levels (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS "DB_schema".users_lists
    ADD FOREIGN KEY (users_id)
    REFERENCES "DB_schema".users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS "DB_schema".users_lists
    ADD FOREIGN KEY (lists_id)
    REFERENCES "DB_schema".lists (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS "DB_schema".lists_tickets
    ADD FOREIGN KEY (lists_id)
    REFERENCES "DB_schema".lists (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS "DB_schema".lists_tickets
    ADD FOREIGN KEY (tickets_id)
    REFERENCES "DB_schema".tickets (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;